#pragma kernel Randomize
#pragma kernel RandomizeStep

RWTexture2D<float4> Result;
float Step;

float random(float2 range)
{
    return frac(sin(dot(range.xy, float2(12.9898, 78.233))) * 43758.5453);
}

[numthreads(8,8,1)]
void Randomize(uint3 id : SV_DispatchThreadID)
{
    Result[id.xy] = float4(random(id.xy).xxx, 1);
}

[numthreads(8,8,1)]
void RandomizeStep(uint3 id : SV_DispatchThreadID)
{
    Result[id.xy] = float4(step(Step, random(id.xy)).xxx, 1);
}
